[package]
name = "rustchat"
version = "0.1.0"
edition = "2024"

[dependencies]
mongodb = { version = "2.8", features = ["tokio-runtime"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }

